name: ci

on:
  push:
    branches:
      - master
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo $GITHUB_WORKSPACE
      - name: Checkout helm-charts
        uses: actions/checkout@v2

        with:
          repository: zkooli/charts
          ref: refs/heads/gh-pages
          path: charts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish the Helm chart
        id: publish-chart
        uses: moikot/chart-publish-action@v1
        with:
          chart: "charts"
          charts_dir: "charts"
          charts_url: "https://zkooli.github.io/charts"
          helm_image: alpine/helm:3.11.1
          
      - name: Commit and push helm-charts
        uses: EndBug/add-and-commit@v6
        with:
          author_name: zied KOOLI
          author_email: janedoe@example.com
          branch: gh-pages
          cwd: charts
          message: "Commit chart ${{ steps.publish-chart.outputs.chart }}"
