name: Release Charts

on:
  push:

    paths:
      - charts/**
      - .github/workflows/release-charts.yaml

  workflow_dispatch:

jobs:
  release:
    env:
      CHART_DIR: charts
      CHART_REPO: zkooli/charts
      CHART_REPO_BRANCH: gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Helm chart repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.CHART_REPO }}
          path: .charts-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq - portable yaml processor
        uses: mikefarah/yq@v4.30.5

      - name: Install chart releaser
        run: |
          set -e
          arch="$(dpkg --print-architecture)"
          curl -s https://api.github.com/repos/helm/chart-releaser/releases/latest \
          | yq --indent 0 --no-colors --input-format json --unwrapScalar \
            ".assets[] | select(.name | test("\""^chart-releaser_.+_linux_${arch}\.tar\.gz$"\"")) | .browser_download_url" \
          | xargs curl -SsL \
          | tar zxf - -C /usr/local/bin
      - name: Install Helm
        uses: azure/setup-helm@v3.4

      - name: Update charts index
        working-directory: .charts-repo
        run: |
          set -ex
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          mkdir -p .cr-index
          owner=$(cut -d '/' -f 1 <<< '${{ github.repository }}')
          repo=$(cut -d '/' -f 2 <<< '${{ github.repository }}')
          cr index --git-repo "$repo" --owner "$owner" --pages-branch '${{ env.CHART_REPO_BRANCH }}' \
            --package-path '../${{ steps.package.outputs.dir }}' \
            --index-path .cr-index --push
